### ISSUE TITLE
Stylesheet / Defaults / overall page width / font size / CSS Reset

### ISSUE THREAD

**Issue by drewwestphal** [drewwestphal/jococruise-theme#10]
@paulnotstorm @gregstormd @jonathancoulton 

compare https://dev.jococruise.com/ with http://macaroniandcruise.com/

Mac and cruise is wider and the fonts are bigger and the images are bigger. I think that makes mac and cruise easier to look at. Should we widen the jcc site on large monitors and beef up font and image sizes more?

**Comment by drewwestphal** [comment]
what do you guys think about this

/cc @paulnotstorm @gregstormd @jonathancoulton

**Comment by divmazie** [comment]
As a related note, the all-news page has a totally inconsistent font size with the single news item page.

**Comment by drewwestphal** [comment]
This is a mondo issue.
