### ISSUE TITLE
Artist Post Type Changes

### ISSUE THREAD

**Issue by paulnotstorm** [drewwestphal/jococruise-theme#11]
Eliminate "Office Hours" category and replace it with "Previous Performer".

Obviously not super-urgent; but it'll save me time later having to go back through all the bios I import and change that setting.

**Comment by drewwestphal** [comment]
Do you see any case for adding a which year box, where we could put in comma separated years people have performed?

**Comment by paulnotstorm** [comment]
Couldn’t hurt to have checkboxes for the different years. Gives us the option, if we feel like it, to sort them by cruise and/or list which cruises they were on.

**Comment by drewwestphal** [comment]
Ok, here are the changes want to make so far:

1) Artist Type Category: replace "Office Hours" with "Previous Performer"... or add "Previous Performer"
2) Add checkboxes for each performer year

Let me know if anything else comes to mind or if I should just do these now.

**Comment by drewwestphal** [comment]
Seems like it would be easiest to just add the Previous Performer category, leaving the rest as is. 

Checkboxes for year might end up being more complex to use on the code side than a textbox with comma delim years? 

Let me know your thoughts on this. Pulling ACF data is annoying.

**Comment by cmd-kae** [comment]
If these are artists and the year is an ACF in the artist post, then I can query and sort by year. It's pretty close to how it's set up now. I don't think it would take too long.

**Comment by paulnotstorm** [comment]
Forgot to update this: based on recent discussions, we'd like to be able to label artists as "Performer" or "Featured Guest" for each year.

So maybe we need a series of checkboxes for each Artist entry: "2015 - Performer", "2015 - Featured Guest", "2014 - Performer", etc.?

**Comment by drewwestphal** [comment]
Add dropdown options
- "Spotlight Item"
- "Not Attending This Year" -- or something -- this is the default

Then the same list of dropdown items are available for every year
