### ISSUE TITLE
Potential EULA violation

### ISSUE THREAD

**Issue by fontpolice** [drewwestphal/jococruise-theme#111]
Dear drewwestphal,

It has come to our attention through [FontFinder](http://www.fontfinder.io) that your hosting of SurveyorDisplay-BookItalic-Pro.otf in this _public_ repository could be a potential violation of the End User License Agreement (EULA) between yourself and the respective foundry.

We recommend that you [remove](https://github.com/blog/1545-deleting-files-on-github) the files to avoid further action.

Sincerely,
The Font Police

**Comment by drewwestphal** [comment]
Hi there 292df97bf08a0e3673635267b4efce44b286c882 removes the fonts. Our apologies.

**Comment by fontpolice** [comment]
Thank you for your cooperation.
