### ISSUE TITLE
Default Page Style

### ISSUE THREAD

**Issue by drewwestphal** [drewwestphal/jococruise-theme#2]
The current default page style is not readable. Please create a default style for pages that is readable similar to the style on the artist page type, but without the special space given to the featured image.

For example at https://dev.jococruise.com/the-cruise/

![image](https://cloud.githubusercontent.com/assets/229646/6699195/10bca1e4-ccd6-11e4-8e36-220bc12fbfdb.png)
![image](https://cloud.githubusercontent.com/assets/229646/6699202/15d4eca4-ccd6-11e4-81a3-5eadbeb8a68e.png)

**Comment by cmd-kae** [comment]
I left out the nav on the bottom bumper here bc of potential issues of context however one solution I thought of was to use the title of its (potential) siblings to instead of next/previous to avoid confusion. In this case, it would show the names of other pages like news, etc.

**Comment by drewwestphal** [comment]
Huh. So you mean that a page like https://dev.jococruise.com/2015/01/3488/ would have the titles of the next and previous articles in the bumper? I like that.

Also, same page https://dev.jococruise.com/2015/01/3488/: the next button is active but there is nothing "next". Can we hide the next button in the case that nothing is next?

**Comment by drewwestphal** [comment]
Also I've been thinking that the style should default to (for pages AND posts)

Do the two up layout with the featured image IFF the featured image exists

Otherwise do the layout like at https://dev.jococruise.com/the-cruise/

**Comment by cmd-kae** [comment]
> So you mean that a page like https://dev.jococruise.com/2015/01/3488/ would have the titles of the next and previous articles in the bumper?

Yep! So further changes discussed here are: conditional article width based on images, conditional links (which should be working unless I just forgot), and use of titles instead of next/previous

Please don't hesitate to let me know if I missed anything!

**Comment by drewwestphal** [comment]
Yup.
