### ISSUE TITLE
Artist Social Feeds

### ISSUE THREAD

**Issue by drewwestphal** [drewwestphal/jococruise-theme#28]
These buttons seem to not being showing up. I can't find them in the ACF export you sent or in the PHP export I did of the export you sent, which is now in the theme file. 

IDK which is easiest for you, but can you either

1) get them working on https://dev.jococruise.com/ whichever way and I can export the php and patch the acf php file 
2) patch the acf php file so this works?

**Comment by cmd-kae** [comment]
I can't poke around wp on dev.joco because I'm not an admin but I can add it to functions and check that in which is easy and shouldn't require work on your end to incorporate, or just send you a file for import. (I could also add all the ACFs to functions if you prefer that idea and don't think it's too messy for future use.)

**Comment by drewwestphal** [comment]
check out includes/acf.php in the theme. i already have an acf php export in there. it's my preferred way of working with that plugin as it keeps other people from messing with or viewing the settings and it submits to version control.

**Comment by drewwestphal** [comment]
oh and i think master has more changes, which you may want to merge into your branch

**Comment by cmd-kae** [comment]
oh that's perfect thank you

**Comment by drewwestphal** [comment]
Hey, can you add this styling to the backend wherever appropriate? 

Right now labels for the fields show up in this dumb way 
![image](https://cloud.githubusercontent.com/assets/229646/6875531/cf41cdd0-d495-11e4-9bbe-9f46bd30b4d3.png)

This will fix it:

```
p.label label {
  display: block;
  font-weight: bold;
}
```

Makes it like this: 
![image](https://cloud.githubusercontent.com/assets/229646/6875527/cb43639c-d495-11e4-9664-2d6ed95a68c0.png)

**Comment by cmd-kae** [comment]
Hmm I can't reproduce this but I think this would be in the plugin css anyway (I think: plugins/acf/css/input.css). If you wanted to include the plugin in the theme (which could be helpful for the future), then I could do that and try to make changes but I can't reproduce it so it would be a shot in the dark.

**Comment by drewwestphal** [comment]
Huh. Ok. Weird.

**Comment by paulnotstorm** [comment]
Also: looking back at this: should we maybe drop the YouTube category (since very few, if any, of our guests currently have a dedicated active YT channel) and turn it into just a Website category?

**Comment by paulnotstorm** [comment]
Bumping this, as it is directly relevant to our lineup announcement this week; can we switch the YouTube category to "Website" (or similar), and give it some sort of relevant icon? Maybe something like the "http:" one in the second row of this set? http://thumbs.dreamstime.com/z/internet-website-icon-ii-2217365.jpg

Or, maybe better: just add another field—and make it come first in the order—for website?
