### ISSUE TITLE
Behavior: Clicking on top bar 

### ISSUE THREAD

**Issue by drewwestphal** [drewwestphal/jococruise-theme#29]
clicking on top bar here
https://dev.jococruise.com/artist/john-hodgman/

takes me here
https://dev.jococruise.com/artist/john-hodgman/#wrapper

it seems like it should take me to the front page

what are your thoughts on this? is the #wrapper behavior intentional?

**Comment by cmd-kae** [comment]
Nope, that's a mistake!
