### ISSUE TITLE
Menu Changes

### ISSUE THREAD

**Issue by drewwestphal** [drewwestphal/jococruise-theme#31]
From Jessie Email 

![image](https://cloud.githubusercontent.com/assets/229646/6872269/86f19f22-d47e-11e4-8427-35074bd97cf9.png)

**Comment by cmd-kae** [comment]
Since it's labeled now, do you want the icon to be a carrot/collapse triangle instead of the basement since it's not using a basement like in the original comps and it is collapsing?

**Comment by drewwestphal** [comment]
Never heard it called a basement before. Apparently also called hamburger. Also apparently a bit of a design anti-pattern according to some blogs who have the time to do stats on all this crap. Jesus the web is just impossible these days.

Anyway, sure, carrot/collapse sounds good to me.

Also can you look at this and see if it's relevant to our site/easy to implement?
http://updates.html5rocks.com/2013/12/300ms-tap-delay-gone-away

**Comment by drewwestphal** [comment]
Oh and can we have the content area that gets bluer be the WHOLE of the menu thing (including the text)? I think that will look better. Something here looks jagged to me. 

And I'd like to decrease the space between the sub items by about half and see how that looks.We are just tight on space.

![image](https://cloud.githubusercontent.com/assets/229646/6872597/aeacf55a-d480-11e4-9465-4f45e3064f49.png)

**Comment by cmd-kae** [comment]
When you say that part that gets bluer, do you mean the text that's active and, if so, does that mean you'd like to see it with a light blue all the way across (like the book now button in the same screenshot)?

**Comment by drewwestphal** [comment]
Oh... interesting.

I meant up top 

![image](https://cloud.githubusercontent.com/assets/229646/6872731/68076490-d481-11e4-8ed7-5f50d87aeea4.png)

I don't want to get too far away from the simplicity of the existing design. I was just trying to avoid the boxy look of having the blue in this screen cap so violently abut the text that says menu. Maybe menu fads out when then triangle is clicked?

**Comment by cmd-kae** [comment]
Oh got it! Thanks for clarifying.

**Comment by drewwestphal** [comment]
Sure thing

**Comment by drewwestphal** [comment]
Do what you think is best here

**Comment by cmd-kae** [comment]
Can do. Thank you.
