### ISSUE TITLE
mobile button line wrap

### ISSUE THREAD

**Issue by drewwestphal** [drewwestphal/jococruise-theme#32]
![image](https://cloud.githubusercontent.com/assets/229646/6872289/b91569a2-d47e-11e4-92bc-998bfef42577.png)

**Comment by drewwestphal** [comment]
only mobile chrome?

**Comment by divmazie** [comment]
This issue is kind of moot currently, give that the text is "Book now!"

**Comment by drewwestphal** [comment]
+PUNT!
