### ISSUE TITLE
About section

### ISSUE THREAD

**Issue by drewwestphal** [drewwestphal/jococruise-theme#33]
From Jessie Eamil

![image](https://cloud.githubusercontent.com/assets/229646/6872308/cec09c9a-d47e-11e4-8ee7-f633cfe050a1.png)

**Comment by drewwestphal** [comment]
/cc @paulnotstorm @gregstormd 

This was added way back. This is what they look like. Wanna test one out one night and see if you want to use?

**Comment by paulnotstorm** [comment]
Seems like this is mostly already covered by the main page top section and the new Experience page.

**Comment by drewwestphal** [comment]
this is not currently used
