### ISSUE TITLE
FAQ items don't auto-expand when linked to

### ISSUE THREAD

**Issue by paulnotstorm** [drewwestphal/jococruise-theme#38]
when clicking on a link from another FAQ item/page, linked FAQ item should automatically expand.

**Comment by divmazie** [comment]
I'm working on this, but want to make a note that some links need to be corrected to the form (/faq/#discount). Some links seem to be missing first slash or have extraneous slash at end.

**Comment by paulnotstorm** [comment]
Tried to catch all those; but if you spot any still left, let me know which ones, and I’m happy to fix.

**Comment by divmazie** [comment]
Thanks, Paul. All my edits are limited to my local development environment until Drew gets stateside again. The ones I spotted were in "Is there an age limit..." and "Can I book the cruise directly...".

**Comment by paulnotstorm** [comment]
Okay, those two are fixed.

**Comment by drewwestphal** [comment]
is fixed
