### ISSUE TITLE
Markdown header levels in pages not working

### ISSUE THREAD

**Issue by paulnotstorm** [drewwestphal/jococruise-theme#39]
Marking text with header markdown ("### This Text Should Be Bigger") doesn't result in any size difference. Need to amend style to include header levels?

**Comment by drewwestphal** [comment]
we'll check this out next week

**Comment by divmazie** [comment]
This is part of our larger style sheet bloat/generalizability issue.

Paul, is there a specific place where this is a problem?

**Comment by paulnotstorm** [comment]
Just created a (private) page for testing it: https://jococruise.com/testing-page/ https://jococruise.com/testing-page/

I guess it’s that there very little difference between level 2 and level 3 header font size.
