### ISSUE TITLE
add field for Artist website to artist social media options

### ISSUE THREAD

**Issue by paulnotstorm** [drewwestphal/jococruise-theme#45]
We have twitter and facebook and youtube, but not website.

**Comment by paulnotstorm** [comment]
Not sure what the icon for it should be, will let you choose that.

**Comment by paulnotstorm** [comment]
This is and #28 are the same (see notes on #28 re: icon for website); if I knew how to combine them, I'd do it.

**Comment by drewwestphal** [comment]
Needs testing to address potential subtle css bug, otherwise this is closed per @divmazie

**Comment by drewwestphal** [comment]
@divmazie you want to test this today? Or move to next milestone? Trying to close down the first perf announce milestone asap.

**Comment by paulnotstorm** [comment]
I entered all these for the performers and guests last night; seems to work fine.

**Comment by divmazie** [comment]
Yeah, I've tested it in all the browsers I have. As long as someone with Windows can take a look at it, I'd say we should just use it how it is. Still a bit of a head scratcher though.

**Comment by drewwestphal** [comment]
Weird. Closing for now
