### ISSUE TITLE
Reformat display of sponsor logos

### ISSUE THREAD

**Issue by paulnotstorm** [drewwestphal/jococruise-theme#51]
Would love to have the page-bottom sponsor listing behave as it does on http://vidcon.com/. Logos re-distribute themselves based on browser width, each logo in its own square, linking to sponsors' sites.

**Comment by drewwestphal** [comment]
storm wants an option to make sponsors double wide... should be doable

**Comment by drewwestphal** [comment]
create a sponsors page as well!

**Comment by drewwestphal** [comment]
max # of sponsors depends on viewport width

overlay sponsors onto white squareish thing

also see vidcon's sponsor page http://vidcon.com/our-sponsors/

**Comment by divmazie** [comment]
I put each sponsor image (from post featured image) in a square grid with links to the sponsor site. They rearrange themselves with viewport resize with bootstrap. Double-wide option isn't there yet. Nor is the sponsor page with more info on each sponsor.

**Comment by drewwestphal** [comment]
Looking great at standard resolution. 

Need to work on mobile display.

1) fix stretching for graphics 
2) more columns

![image](https://cloud.githubusercontent.com/assets/229646/8060364/dad94dbc-0e92-11e5-983b-c3df84a54d7c.png)

Also I made a small change in your branch. Note b9fc77d1109605e97fe098e283e52b5a70eddfe9. It was mentioned that perhaps the hardcoded image size could be causing some of the display issues we noticed.

**Comment by drewwestphal** [comment]
Safari issues apparently result of caching

**Comment by divmazie** [comment]
I'm not able to reproduce the same stretching problem that you screen shotted above. And my solution is based on a fixed square size, so I can't increase the number of columns without shrinking the square size further which I think would look worse overall.

**Comment by drewwestphal** [comment]
I still get this. This is on the live site with the last from the master
branch.

[image: Inline image 1]
