### ISSUE TITLE
Line spacing in ul and ol

### ISSUE THREAD

**Issue by paulnotstorm** [drewwestphal/jococruise-theme#54]
Line spacing in list items is 1.5, needs to be restored to single spacing.

Specifically, this is for individual list items that wrap beyond one line. Spacing between list items and before/after lists is fine as it is currently.

See https://jococruise.com/im-booked-now-what/ for examples.

**Comment by drewwestphal** [comment]
This is partially fixed More to come per @divmazie

**Comment by drewwestphal** [comment]
new styles should fix
