### ISSUE TITLE
horizontal rule not showing up on "I'm Booked, Now What?" page

### ISSUE THREAD

**Issue by paulnotstorm** [drewwestphal/jococruise-theme#55]
There's an space inserted for the code, but no actual horizontal rule.

**Comment by drewwestphal** [comment]
this is the page in question 

https://jococruise.com/im-booked-now-what/

![image](https://cloud.githubusercontent.com/assets/229646/7641229/6156f89a-fa56-11e4-885d-230403eb70fc.png)

should appear here. is in source, but unstyled.... DAMN CSS RESET

**Comment by drewwestphal** [comment]
![image](https://cloud.githubusercontent.com/assets/229646/7641250/774ac85c-fa56-11e4-89fb-2858226e325d.png)

**Comment by divmazie** [comment]
I see this rendering as a ship and rope graphic. Is this wrong?

**Comment by drewwestphal** [comment]
I believe this has already been addressed, perhaps. Does it appear on all
pages? A screenie?

**Comment by paulnotstorm** [comment]
This shows up now, you can close this issue.
