### ISSUE TITLE
Add "2016 PERFORMERS" Separator text for performer section of main page

### ISSUE THREAD

**Issue by paulnotstorm** [drewwestphal/jococruise-theme#56]
Same format as "2016 FEATURED GUESTS" separator, but at beginning of performers.

**Comment by drewwestphal** [comment]
Ignore missing images. They are not currently present in my dev environment.

Like this?

![image](https://cloud.githubusercontent.com/assets/229646/7618616/45dfd4cc-f981-11e4-9676-65c2aebb9e90.png)

**Comment by paulnotstorm** [comment]
Make it just “2016 PERFORMERS” and drop the “featured”.

Otherwise awesome.

Also, love the message window content. :)

**Comment by drewwestphal** [comment]
Thought you would

<3!

**Comment by drewwestphal** [comment]
![image](https://cloud.githubusercontent.com/assets/229646/7618871/0164d976-f983-11e4-8a2f-8a3400315cdb.png)

**Comment by paulnotstorm** [comment]
Ding!
