### ISSUE TITLE
Have "2016 FEATURED GUESTS" separator begin new row

### ISSUE THREAD

**Issue by paulnotstorm** [drewwestphal/jococruise-theme#57]
regardless of whether there's space left on the row above it.

Adduming this isn't a huge pain, of course.

**Comment by divmazie** [comment]
Fix here -> 12fb783c3574ba20e98b32fa64ad413d70106562

Same thing was done for Track events here -> 8d2c556b6a0cc84f4c6678ca40191b81cab21cc4

**Comment by drewwestphal** [comment]
@paulnotstorm please check front page, reopening if further issues
