### ISSUE TITLE
Experience page - photos overlapping page text

### ISSUE THREAD

**Issue by paulnotstorm** [drewwestphal/jococruise-theme#60]
photos in the gallery beyond a certain height overlap the page text below it. Set a max height for all gallery photos, I guess.

**Comment by divmazie** [comment]
Can you screen cap an example and tell me what browser you're using? I thought what I had written handled this.

**Comment by paulnotstorm** [comment]
Using Chrome on OS X 10.10.3...

![screen shot 2015-05-14 at 11 54 29 am](https://cloud.githubusercontent.com/assets/9629242/7635614/05353d04-fa30-11e4-9bb5-8f2d75aa33e7.png)
![screen shot 2015-05-14 at 11 54 18 am](https://cloud.githubusercontent.com/assets/9629242/7635613/05354e20-fa30-11e4-92ab-eb0609ddf630.png)

**Comment by divmazie** [comment]
Thanks, Paul. A good example of why cross-browser testing is important. I've got a jQuery fix in the dmexpfixes branch.

**Comment by drewwestphal** [comment]
This fix is live
