### ISSUE TITLE
new "subsection" for Gaming Track and Writing Track icons under "Performers and Featured Guests"

### ISSUE THREAD

**Issue by paulnotstorm** [drewwestphal/jococruise-theme#61]
After the "2016 Featured Guests" section of the Performer listing, add another "text divider" saying "PLUS", and move the "Gaming Track Events" and "Writing Track Events" icons there (instead of under the "Performers" section where they are currently.

The "PLUS MORE TO COME" divider will still be at the very end.

**Comment by drewwestphal** [comment]
create another category for spotlight item with its own header banner thing that says "plus even more" or something 

add some editable paragraph section at the beginning too 

![image](https://cloud.githubusercontent.com/assets/229646/7640686/b333b026-fa52-11e4-8ced-6cfae3e7dde5.png)

**Comment by drewwestphal** [comment]
New artist type: "Spotlight Item" 
Influence ordering based on new cat addition
Add new "Header" thing that says, to start, "plus even more"

**Comment by paulnotstorm** [comment]
Related: at your convenience, can you forward the gaming track and writing track icons that Jessie made? (The ones currently on the Experience page)

**Comment by drewwestphal** [comment]
Here they are in a vector format I've never seen before.

@divmazie, could you upload higher res (vector?) art to the site for max
retina fidelity?

**Comment by drewwestphal** [comment]
Hey @paulnotstorm  This is starting to look pretty weird. I think we may have stretched this format a bit

Thoughts? 

![image](https://cloud.githubusercontent.com/assets/229646/7642703/3f4965e8-fa61-11e4-89d0-445232611c1f.png)

![image](https://cloud.githubusercontent.com/assets/229646/7642710/4990893c-fa61-11e4-8a87-803aee699e19.png)

![image](https://cloud.githubusercontent.com/assets/229646/7642714/500bc1be-fa61-11e4-83eb-272f794974b7.png)

**Comment by divmazie** [comment]
cb66682d9d96b9d532265903cc8b564b92fd5809

**Comment by paulnotstorm** [comment]
Assuming we're adding a "more to come" sentence at the end as you mentioned, I think we can drop the "Plus MORE TO COME SOON" end divider. I'd also change the "PLUS EVEN MORE" to either just "PLUS" or maybe "TRACK EVENTS".

It's a long section, but it doesn't really bother me terribly. Kind of impressive the size of the lineup, actually.

**Comment by drewwestphal** [comment]
Hey @paulnotstorm check out the front page and reopen if this is no good.
