### ISSUE TITLE
Slider Pos on Exp Page

### ISSUE THREAD

**Issue by drewwestphal** [drewwestphal/jococruise-theme#64]
Seems to not be moving down with content. 

![image](https://cloud.githubusercontent.com/assets/229646/7640339/b1e5d6e2-fa50-11e4-9cfe-2936e7dec56c.png)

**Comment by drewwestphal** [comment]
Is this something that css is making difficult? If so what we've got is fine for now and we can push this to next milestone. 

If not, I'd love to see them sitting a little teensy bit above vert center in the rounded images. 

![image](https://cloud.githubusercontent.com/assets/229646/7653810/90bfb01e-fae6-11e4-82d0-d09033d3309b.png)

**Comment by divmazie** [comment]
Tweaked them a bit higher: cb62be1cf8e2a0c00bc9bf9b8d9a7788e0c71c72

My judgment changes slightly based on how long the text is.

**Comment by drewwestphal** [comment]
more sliders this is closed fo rnow
