### ISSUE TITLE
uniform height for photo carousel

### ISSUE THREAD

**Issue by drewwestphal** [drewwestphal/jococruise-theme#65]
they don't go crazy on the height, but it's not uniform

perhaps set a frame of some sort into which the image must fit along its less conforming axis? for short ones center? or stretch? make sure it's larger wrt viewport but not too large so as not to fit on the screen. 

doable? 

![image](https://cloud.githubusercontent.com/assets/229646/7640386/fb23154a-fa50-11e4-9b4b-5cdb5c1f2fb3.png)
![image](https://cloud.githubusercontent.com/assets/229646/7640392/ff77d55e-fa50-11e4-8788-e2a928177362.png)

**Comment by drewwestphal** [comment]
also a note from paul: he likes the carousel without the slidey action, which honestly i do too. so this we don't need to touch

**Comment by drewwestphal** [comment]
added benefit of this change is allows for arrows to stay at pretty location wrt content

**Comment by drewwestphal** [comment]
for now believe this is closed-- @paulnotstorm ?

**Comment by paulnotstorm** [comment]
Yup.
