### ISSUE TITLE
exp page: update list of performers

### ISSUE THREAD

**Issue by drewwestphal** [drewwestphal/jococruise-theme#67]
/cc @paulnotstorm will provide 
in a text file with one performer full name as he wants it to appear per line

![image](https://cloud.githubusercontent.com/assets/229646/7640794/6dd19736-fa53-11e4-898f-a404c0bc4777.png)

**Comment by paulnotstorm** [comment]
Jonathan Coulton
Jim Boggia
The Both - Aimee Mann and Ted Leo
Rhea Butcher
Marian Call
Chris Collingwood
Bill Corbett and Kevin Murphy
The Doubleclicks
John Flansburgh
Jean Grae
Vi Hart
John Hodgman
Matthew Inman
Steve Jackson
Zoë Keating
Hari Kondabolu
Molly Lewis
Merlin Mann
MC Frontalot
Opus Moreschi
Randall Munroe
Paul and Storm
Mike Phirman
David Rees
John Roderick
Patrick Rothfuss
Peter Sagal
John Scalzi
Joseph Scrimshaw
Paul F. Tompkins
Stephen "Stepto" Toulouse
Wil Wheaton

**Comment by drewwestphal** [comment]
This appears good for now. Hopefully past artists pull will be working before another update is requested.
