### ISSUE TITLE
add about section from mac and cruise back in 

### ISSUE THREAD

**Issue by drewwestphal** [drewwestphal/jococruise-theme#7]
we'd like to do the same deal as m&c with alternating sea & white text and image, proper scaling etc in the theme. likely we will only add one section like this. we will likely swap out the ocean bg image, but can you implement the functionality?

**Comment by cmd-kae** [comment]
can do

**Comment by drewwestphal** [comment]
status?

**Comment by cmd-kae** [comment]
in progress
