### ISSUE TITLE
"Shadow cruise" experience piece: line spacing and list formatting

### ISSUE THREAD

**Issue by paulnotstorm** [drewwestphal/jococruise-theme#73]
In the "Shadow cruise section, a double space is appearing on the page as a single space.

Also, an unordered list is appearing just as centered text.

![screen shot 2015-05-14 at 11 24 01 pm](https://cloud.githubusercontent.com/assets/9629242/7646379/8e2d2ca6-fa90-11e4-9245-36a6b379cd94.png)

![screen shot 2015-05-14 at 11 25 58 pm](https://cloud.githubusercontent.com/assets/9629242/7646382/9d03cdb6-fa90-11e4-8c09-d903cf49d2ca.png)

**Comment by drewwestphal** [comment]
This was also in the designs--the centered text that is.

I will check out the <p> styling here and add some space!

DRew

**Comment by drewwestphal** [comment]
Hey Paul, spacing is added. 

aa376282daf269191a705be3a9fc4560de8fa0f3

What you think about UL centering? 

Here's a screeny of the design psd for relevant section 

![image](https://cloud.githubusercontent.com/assets/229646/7653758/239cee16-fae6-11e4-9527-72117688d328.png)

And here is the whole deal for reference 

![joco_fullscreen_experience_v2_1](https://cloud.githubusercontent.com/assets/229646/7653763/2ee9138a-fae6-11e4-9eb1-85ec73a399fd.jpg)

**Comment by paulnotstorm** [comment]
Spacing issue made moot by someone revising the section without an extra paragraph up top; but good to know.

Centered list: Doesn’t bug me terribly if it doesn’t bug anyone else particularly. Mostly a personal preference issue, but it doesn’t bother me the way it did yesterday. Mostly it threw me off because the “more information and links” section formats the list “normally." 

cc:ing Storm for his thoughts on it. If he is fine with it, consider this issue closed.

**Comment by drewwestphal** [comment]
gotta @ him to get him emailed @gregstormd

**Comment by paulnotstorm** [comment]
Sorry; was using my actual email, not the github interface. I'll send it (and a question re a couple other issues) in a separate email.
