### ISSUE TITLE
Move text for "Photos and Videos" experience piece below title

### ISSUE THREAD

**Issue by paulnotstorm** [drewwestphal/jococruise-theme#74]
Body text is currently above title:

![screen shot 2015-05-14 at 11 45 56 pm](https://cloud.githubusercontent.com/assets/9629242/7646576/82581212-fa93-11e4-8d9c-784b346acef8.png)

Should go below title and be justified similar to earlier sections.
![screen shot 2015-05-14 at 11 47 40 pm](https://cloud.githubusercontent.com/assets/9629242/7646585/a6796c90-fa93-11e4-83b3-7d6d8cc96800.png)

**Comment by drewwestphal** [comment]
Hey Paul, this is called from from the designs. It seems you got the video to layout in the gallery section. Does that work? 

Do you still want this change?

**Comment by paulnotstorm** [comment]
Video is working fine, I think.

Will ask storm about his thoughts about the text vs. title thing. If it doesn’t bug him, I’m good with it Either way, I don’t think it’s necessary to fix before the announcement.

**Comment by paulnotstorm** [comment]
Glorious.

Need another that says “LARAMIE, WYOMING"

**Comment by drewwestphal** [comment]
this is resolved

current plan is to combine the two posts for the photo section at some point, since the content fro section 1 is no longer in use
