### ISSUE TITLE
slider location still wonky?

### ISSUE THREAD

**Issue by drewwestphal** [drewwestphal/jococruise-theme#78]
this is on the live site

![image](https://cloud.githubusercontent.com/assets/229646/7653719/e751cb66-fae5-11e4-836b-bbb726c7bdf7.png)

**Comment by paulnotstorm** [comment]
I’m assuming you’re asking they be more centered vertically? (In which case I agree)

**Comment by drewwestphal** [comment]
yes indeed

**Comment by drewwestphal** [comment]
is there a more robust solution for sliders in the future or are we good? moving to may milestone to investigate.

**Comment by divmazie** [comment]
Yeah, I'm going to lump this is with the needing a more general solution for carousels.

**Comment by drewwestphal** [comment]
part of new carousels
