### ISSUE TITLE
create all artists page

### ISSUE THREAD

**Issue by drewwestphal** [drewwestphal/jococruise-theme#8]
we'd like a page that shows every artist in the database, even those who aren't assigned to a category

the page should just be a buncha circles and pics, as if it were just a giant artists section on the front page. same bg &c.

only other thing we need is a header for the page & some copy. You can do it like the faq, where we just pick a page with a given slug and append all the artist stuff to the bottom

![image](https://cloud.githubusercontent.com/assets/229646/6699642/5f57f1b0-ccda-11e4-9c6b-fd5df521329f.png)

**Comment by cmd-kae** [comment]
Would you like a link to the Artists page at the bottom of the front-page section like _View All Artists_ à la View All News, View All FAQs, etc.?

**Comment by paulnotstorm** [comment]
My first instinct is no, because we’ll be listing all our artists in that section, not just a sampling.

**Comment by drewwestphal** [comment]
No we don't want that from the front page. We'll be listing ALL of them,
even the ones from past cruises.
