### ISSUE TITLE
Experience page - bg color of More Info/Links experience piece same as previous section

### ISSUE THREAD

**Issue by paulnotstorm** [drewwestphal/jococruise-theme#83]
Switch bg color of More Info piece to either the off-white of the "What is the JoCoCruise" piece, or darker color of the "Shadow Cruise" piece.

Super-not-urgent issue.

**Comment by drewwestphal** [comment]
Don't want to do this today because it will make the boat icon look weird. Please advise for future. /cc @gregstormd 

![image](https://cloud.githubusercontent.com/assets/229646/7656908/d01dbd5e-fafb-11e4-834b-7bff81087f8e.png)

**Comment by paulnotstorm** [comment]
The only section I wanted the color changed was the More Info/Links section (since it has the same bg color as the Photo/Video section prior to it.

![screen shot 2015-05-15 at 12 16 21 pm](https://cloud.githubusercontent.com/assets/9629242/7656981/3f231546-fafc-11e4-8d6c-c088667933b6.png)

I only referenced the What Is JoCo Cruise section as a reference for which bg color you could use for it.

Sorry for any confusion. /cc: @gregstormd

**Comment by paulnotstorm** [comment]
Either way, doesn't need to be fixed pre-announcement. cc: @gregstormd
