### ISSUE TITLE
inserting a captioned "byline image" into news posts

### ISSUE THREAD

**Issue by paulnotstorm** [drewwestphal/jococruise-theme#88]
We are having a guest blogger who will be posting occasionally (1-2 times a month) whom we want to add a "byline" captioned photo to the top of her posts.

Two options, each with their own pros and cons:

Option 1) It could be a right-aligned, captioned photo inserted into the post. If so, we need to enable align right with text-wrapping for images embedded in posts. Currently it looks like this:

![screen shot 2015-05-19 at 2 38 23 pm](https://cloud.githubusercontent.com/assets/9629242/7710868/beef2a18-fe34-11e4-8a37-c79db1e2dd80.png)

The other problem with going this route is that the embedded picture shows up on the front page "News" section:

![screen shot 2015-05-19 at 2 38 52 pm](https://cloud.githubusercontent.com/assets/9629242/7710894/f90f4f16-fe34-11e4-95f0-f240a608f349.png)

Is there a way to get the embedded pic to not be displayed on the main page?

Option 2) Use a Featured Image. If we do this, can we activate the "featured image caption" option that's currently available on the "What is the JoCo Cruise" page? 

Also, using Featured Image in the post currently narrows the entire post, instead of the text just wrapping around until past the image. It currently looks like this:

![screen shot 2015-05-19 at 3 20 17 pm](https://cloud.githubusercontent.com/assets/9629242/7711763/b8c1cee2-fe3a-11e4-86e9-9129b4a13f85.png)

Also would want the featured image for these blog posts to be on the right side, rather than on the left where it is currently.

Of course, we'd want these formatting changes to only relate to these news posts; the Artist entries and such should stay as they are.

So then, choose which you think is the easier solution and let me know. Sorry this minor thing is so damn complicated.

P.

**Comment by divmazie** [comment]
Hey Paul, we went with Option 3 on this one. I've added a custom field on posts for a byline name and byline image that adds a thumbnail sized image to the right just below the title that the text wraps around.

**Comment by paulnotstorm** [comment]
Awesome; let me know when the change is live, and I will play with it a bit.

Many thanks for the quick turnaround.
