### ISSUE TITLE
italics, bolds, list styling to: front page, artist bios

### ISSUE THREAD

**Issue by drewwestphal** [drewwestphal/jococruise-theme#9]
the front page currently does not support italics and bolds and stuff in post content (i.e. it does not show them)

please add this

![image](https://cloud.githubusercontent.com/assets/229646/6699673/9aca265a-ccda-11e4-8329-20aac9cc631d.png)

**Comment by paulnotstorm** [comment]
Related: same formatting issues for artist bios as well (I'm assuming this is all part of the same issue), and also doesn't support lists.

**Comment by cmd-kae** [comment]
I think this was fixed with: https://github.com/drewwestphal/jococruise-theme/commit/84762bab66a3e70c577e5265ce18968981ee4c62

But please let me know if you find any instances of this not working.

**Comment by drewwestphal** [comment]
We would like list styling added back as well 

![image](https://cloud.githubusercontent.com/assets/229646/6720523/fe451f4a-cd99-11e4-9ba7-5571c85a9624.png)

**Comment by cmd-kae** [comment]
I introduced a problem with menu padding
