### ISSUE TITLE
add padding

### ISSUE THREAD

**Issue by drewwestphal** [drewwestphal/jococruise-theme#98]
should they be centered?

![image](https://cloud.githubusercontent.com/assets/229646/8482082/3dbcc434-20b5-11e5-939a-f9cfd22e28e3.png)

**Comment by drewwestphal** [comment]
here too? 

![image](https://cloud.githubusercontent.com/assets/229646/8482098/5712e904-20b5-11e5-9bc9-8e0fcd51964c.png)

**Comment by paulnotstorm** [comment]
If we were able to get the news stories full-justified instead of centered, that’d be nice.
